services:
    mysql:
        image: mysql:8.0.35
        container_name: ${MYSQL_CONTAINER_NAME}
        restart: unless-stopped
        env_file:
            - .env
        environment:
            TZ: ${TZ}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        ports:
            - "3306:3306"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
            interval: 5s
            timeout: 10s
            retries: 10
        volumes:
            - internal_volume:/var/lib/mysql
        networks:
            - internal_network

volumes:
    internal_volume:
        name: ${MYSQL_VOLUME}

networks:
    internal_network:
        external: true
        name: ${NETWORK}
