# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyFirstProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyFirstProject

	pod 'Alamofire'

  target 'MyFirstProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyFirstProjectUITests' do
    # Pods for testing
  end

end
